name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Java and Android SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 📀 Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: 📂 Configure Keystore (If Available)
        env:
          STORE_FILE_BASE64: ${{ secrets.STORE_FILE_BASE64 }}
        run: |
          if [ -n "$STORE_FILE_BASE64" ]; then
            echo "$STORE_FILE_BASE64" | base64 --decode > app/keystore.jks
          fi

      - name: 🚀 Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: ✅ Run Tests and Lint Checks
        run: ./gradlew test lint

      - name: 📦 Generate AAB (Android App Bundle)
        run: ./gradlew bundleRelease

      - name: 📤 Upload APK and AAB as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-Output
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab