name: Run Test

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🔧 Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant executable permission to Gradlew
        run: chmod +x gradlew

      - name: Run Unit tests
        run: ./gradlew clean testDebug